table 'Customer Information'
	lineageTag: b910de6a-52bf-48d3-9c53-1802c7019084

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 5dd18bfc-744e-41e6-8c71-3c14073d3e93
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Prefix
		dataType: string
		lineageTag: 21c9210b-01c9-427c-a30b-c81766111149
		summarizeBy: none
		sourceColumn: Prefix

		annotation SummarizationSetBy = Automatic

	column BirthDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8347abc6-943a-48f4-98bc-2c0f6bc19a99
		summarizeBy: none
		sourceColumn: BirthDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MaritalStatus
		dataType: string
		lineageTag: 144e26a8-2c88-44b8-97a8-07979bb42374
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: be25bbc3-d462-43e1-8fab-3f3c83cfa352
		summarizeBy: none
		sourceColumn: Gender

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EmailAddress
		dataType: string
		lineageTag: 9557903c-0e02-47ff-9277-78e2857898a0
		summarizeBy: none
		sourceColumn: EmailAddress

		annotation SummarizationSetBy = Automatic

	column AnnualIncome
		dataType: int64
		formatString: 0
		lineageTag: d4b983db-d5c9-43f7-b9d6-3b8afb5db278
		summarizeBy: none
		sourceColumn: AnnualIncome

		annotation SummarizationSetBy = Automatic

	column TotalChildren
		dataType: int64
		formatString: 0
		lineageTag: fb7cd351-c9d1-453d-804a-1f002d4a1b36
		summarizeBy: none
		sourceColumn: TotalChildren

		annotation SummarizationSetBy = Automatic

	column EducationLevel
		dataType: string
		lineageTag: 6cd6d1fb-d0b8-400c-a524-8518dce7faf6
		summarizeBy: none
		sourceColumn: EducationLevel

		annotation SummarizationSetBy = Automatic

	column Occupation
		dataType: string
		lineageTag: fbf7577e-b080-4b80-a5f7-3fb4bee67d86
		summarizeBy: none
		sourceColumn: Occupation

		annotation SummarizationSetBy = Automatic

	column HomeOwner
		dataType: string
		lineageTag: 4a4d11f4-0988-46ee-9dbe-2a3a8dd59649
		summarizeBy: none
		sourceColumn: HomeOwner

		annotation SummarizationSetBy = Automatic

	column FullName
		dataType: string
		lineageTag: 1c973b1e-ac3b-48e1-9168-b7eb7cbddca5
		summarizeBy: none
		sourceColumn: FullName

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: cb022036-eb7d-4b11-9896-b2767b529f81
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Age_Group
		dataType: string
		lineageTag: b731ee41-67bb-4f95-a4b9-40b659fe88e3
		summarizeBy: none
		sourceColumn: Age_Group

		annotation SummarizationSetBy = Automatic

	column 'First Purchase Date' = ```
			
			CALCULATE(
			    MIN(SalesData[OrderDate]),
			    FILTER(
			        SalesData,
			        SalesData[CustomerKey] = 'Customer Information'[CustomerKey]
			    )
			)
			
			
			
			```
		formatString: General Date
		lineageTag: 2fa1142d-7823-4593-931e-574e06a31f89
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Last Purchase Date' = ```
			
			CALCULATE(
			    MAX(SalesData[OrderDate]),
			    FILTER(SalesData, SalesData[CustomerKey] = 'Customer Information'[CustomerKey])
			)
			
			```
		formatString: General Date
		lineageTag: 7c687f78-e7fa-4ffa-a9c2-49fb64608771
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Customer Revenue Rank' = ```
			
			RANKX(
			    ALL('Customer Information'),
			    'Customer Information'[Customer Total Revenue],
			    ,
			    DESC,
			    Dense
			    )
			
			```
		formatString: 0
		lineageTag: edbcd081-4935-439c-8c9a-f29f717632ea
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Customer Total Revenue' =
			
			CALCULATE(
			    [Total Revenue],
			    ALLEXCEPT('Customer Information','Customer Information'[CustomerKey]))
		lineageTag: 18a3d487-c16a-42bd-baa3-ee4fb65e2092
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Customer Category' =
			
			SWITCH(
			    TRUE(),
			    'Customer Information'[Customer Revenue Rank] <= ROUND(DISTINCTCOUNT('Customer Information'[CustomerKey]) * 0.1, 0), "High Value",
			    'Customer Information'[Customer Revenue Rank] <= ROUND(DISTINCTCOUNT('Customer Information'[CustomerKey]) * 0.2,0), "Medium Value",
			    "Low Value"
			)
		lineageTag: 1303d1c4-79e9-4ab7-a28a-cf5342bac81d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Customer Information' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\new work space\All Class Video\power bi academy course\Adventure Works Project-20250803T155554Z-1-001\Adventure Works Project\AdventureWorks Customer Lookup.csv"),[Delimiter=",", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerKey", Int64.Type}, {"Prefix", type text}, {"FirstName", type text}, {"LastName", type text}, {"BirthDate", type date}, {"MaritalStatus", type text}, {"Gender", type text}, {"EmailAddress", type text}, {"AnnualIncome", Int64.Type}, {"TotalChildren", Int64.Type}, {"EducationLevel", type text}, {"Occupation", type text}, {"HomeOwner", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","","--",Replacer.ReplaceValue,{"Prefix"}),
				    #"Removed Top Rows" = Table.Skip(#"Replaced Value",1),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Removed Top Rows"),
				    #"Removed Top Rows1" = Table.Skip(#"Removed Errors",1),
				    #"Removed Bottom Rows" = Table.RemoveLastN(#"Removed Top Rows1",1),
				    #"Merged Columns" = Table.CombineColumns(#"Removed Bottom Rows",{"FirstName", "LastName"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"Merged"),
				    #"Renamed Columns" = Table.RenameColumns(#"Merged Columns",{{"Merged", "FullName"}}),
				    #"Inserted Age" = Table.AddColumn(#"Renamed Columns", "Age", each Date.From(DateTime.LocalNow()) - [BirthDate], type duration),
				    #"Calculated Total Years" = Table.TransformColumns(#"Inserted Age",{{"Age", each Duration.TotalDays(_) / 365, type number}}),
				    #"Rounded Down" = Table.TransformColumns(#"Calculated Total Years",{{"Age", Number.RoundDown, Int64.Type}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Rounded Down", "Age_Group", each if [Age] < 18 then "0-18" else if [Age] <= 30 then "19-30" else if [Age] <= 50 then "31-50" else if [Age] <= 65 then "51-65" else if [Age] <= 90 then "66-90" else if [Age] <= 115 then "91-115" else "Unknown"),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Conditional Column",{"CustomerKey", "Prefix", "FullName", "BirthDate", "Age", "Age_Group", "MaritalStatus", "Gender", "EmailAddress", "AnnualIncome", "TotalChildren", "EducationLevel", "Occupation", "HomeOwner"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Reordered Columns","","F",Replacer.ReplaceValue,{"Gender"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","NA","M",Replacer.ReplaceText,{"Gender"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","f","F",Replacer.ReplaceText,{"Gender"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value3",{{"Gender", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

