table 'KPIs Profit'
	lineageTag: 3d69c1d0-249e-4961-8c37-37d3f87419a7

	measure 'Total Cost' = SUMX(SalesData, SalesData[OrderQuantity]* RELATED('Product Information'[ProductCost]))
		lineageTag: f2968783-9a9a-49d9-9a5d-1aca07eef283

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Profit' = [Gross Revenue]-[Total Cost]
		lineageTag: f9fe2010-2358-463e-9682-cadaaa9a3df6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit Margin (%)' = DIVIDE([Gross Profit],[Gross Revenue],0)
		lineageTag: 6cd2c977-1993-45e6-adba-7c7b718e671d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit Per Unit' = DIVIDE([Gross Profit],[Total Units Sold])
		lineageTag: eeb47935-b267-4e42-b3d5-c5aa8a1b98a1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Profit' = [Gross Profit]- [Net Profit Loss]
		lineageTag: de304f92-041e-495f-9295-fe3fd70a6d84

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column
		formatString: 0
		lineageTag: da73c31b-07ed-4b89-a1b5-591e0176bdd4
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'KPIs Profit' = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 825403280b8d40cab7a3d7049bf735b8

