table 'KPIs for Card'
	lineageTag: 6956b593-a4a6-46c7-a048-0746c78bb160

	measure PreviousSales =
			CALCULATE(
			    [Total Revenue],
			    DATEADD('Calendar'[Date],-1,YEAR)
			)
		lineageTag: ef209bcf-79db-416e-bd89-05ad00a5281d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales Change %' = ```
			
			VAR _Current = [Total Revenue]
			VAR Previous = [PreviousSales]
			RETURN
			IF(
			    NOT(ISBLANK(Previous)),
			    DIVIDE(_Current - Previous, Previous),
			    BLANK()
			)
			
			```
		lineageTag: 1ae9059e-2037-4fa6-84f5-15519728f5e9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales Comparison' = ```
			
			VAR Prev = [PreviousSales] / 1000000
			VAR Change = [Sales Change %]
			VAR Arrow = IF(Change < 0, UNICHAR(9660), UNICHAR(9650))  // ▼ or ▲
			RETURN
			"vs prev: " & FORMAT(Prev, "0.0") & "M / " & Arrow & FORMAT(Change, "0.0%")
			
			
			```
		lineageTag: fd0bfa86-770c-4870-bf9c-e1eeae717c43

	measure 'Previous Orders' =
			CALCULATE(
			    [Total Orders],
			    DATEADD('Calendar'[Date],-1, YEAR
			    ))
		formatString: 0
		lineageTag: 3feb6644-d10f-4dd4-9281-0a30cf4b91ca

	measure 'Orders Change %' =
			
			VAR _Current = [Total Orders]
			VAR Previous = [Previous Orders]
			RETURN
			IF(
			    NOT(ISBLANK(Previous)),
			    DIVIDE(_Current - Previous, Previous),
			    BLANK()
			)
		lineageTag: 46ccab8a-ac01-4caa-90dd-da763979f2ee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Orders Comparison' =
			
			VAR Prev = [Previous Orders]
			VAR Change = [Orders Change %]
			VAR Arrow = IF(Change < 0, UNICHAR(9660), UNICHAR(9650))  // ▼ or ▲
			RETURN
			"vs prev: " & FORMAT(Prev, "0.0") & "K / " & Arrow & FORMAT(Change, "0.0%")
		lineageTag: d12bdf92-177f-4ed2-b985-c2cae70551b2

	measure PreviousSoldUnits =
			CALCULATE(
			    [Total Units Sold],
			    DATEADD('Calendar'[Date],-1,YEAR)
			)
		formatString: 0
		lineageTag: 34cf6f36-a7e3-4011-af44-e5eb88f337a9

	measure PreviousProfit =
			CALCULATE(
			    [Total Profit],
			    DATEADD('Calendar'[Date],-1,YEAR)
			)
		lineageTag: e5772068-c292-4496-96ec-6a4658397707

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PreviousReturn =
			CALCULATE(
			    [Total Units Returns],
			    DATEADD('Calendar'[Date],-1,YEAR)
			)
		formatString: 0
		lineageTag: 81dc3cce-92e1-4f6c-998e-086ea4e1b489

	measure PreviousReturnRate(%) =
			CALCULATE(
			    [Return Rate (%)],
			    DATEADD('Calendar'[Date],-1,YEAR)
			)
		lineageTag: 73e14cba-bf28-466d-ba58-6003e73418ee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sold Units Change %' =
			
			VAR _Current = [Total Units Sold]
			VAR Previous = [PreviousSoldUnits]
			RETURN
			IF(
			    NOT(ISBLANK(Previous)),
			    DIVIDE(_Current - Previous, Previous),
			    BLANK()
			)
		lineageTag: 7d85b0fa-bd20-488a-9ce9-2686a4874f49

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit Change %' =
			
			VAR _Current = [Total Profit]
			VAR Previous = [PreviousProfit]
			RETURN
			IF(
			    NOT(ISBLANK(Previous)),
			    DIVIDE(_Current - Previous, Previous),
			    BLANK()
			)
		lineageTag: 696267d0-42c6-4dc1-9843-baf70c818f54

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Return Change %' =
			
			VAR _Current = [Total Units Returns]
			VAR Previous = [PreviousReturn]
			RETURN
			IF(
			    NOT(ISBLANK(Previous)),
			    DIVIDE(_Current - Previous, Previous),
			    BLANK()
			)
		lineageTag: 2052add3-7cc1-4586-a57d-e38b54cef662

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Return Rate Change %' =
			
			VAR _Current = [Return Rate (%)]
			VAR Previous = [PreviousReturnRate(%)]
			RETURN
			IF(
			    NOT(ISBLANK(Previous)),
			    DIVIDE(_Current - Previous, Previous),
			    BLANK()
			)
		lineageTag: 9dd491a5-7521-4f69-8822-5dbcc4d28667

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sold Units Comparison' =
			
			VAR Prev = [PreviousSoldUnits]
			VAR Change = [Sold Units Change %]
			VAR Arrow = IF(Change < 0, UNICHAR(9660), UNICHAR(9650))  // ▼ or ▲
			RETURN
			"vs prev: " & FORMAT(Prev, "0.0") & "K / " & Arrow & FORMAT(Change, "0.0%")
		lineageTag: ffb91f12-3f71-49d6-bc3d-f60f3d3bc881

	measure 'Profit Comparison' =
			
			VAR Prev = [PreviousProfit] / 1000000
			VAR Change = [Profit Change %]
			VAR Arrow = IF(Change < 0, UNICHAR(9660), UNICHAR(9650))  // ▼ or ▲
			RETURN
			"vs prev: " & FORMAT(Prev, "0.0") & "M / " & Arrow & FORMAT(Change, "0.0%")
		lineageTag: 9a0c4e60-06ae-4198-a48f-df348d5cb1d1

	measure 'Return Comparison' =
			
			VAR Prev = [PreviousReturn]
			VAR Change = [Return Change %]
			VAR Arrow = IF(Change < 0, UNICHAR(9660), UNICHAR(9650))  // ▼ or ▲
			RETURN
			"vs prev: " & FORMAT(Prev, "0.0") & "K / " & Arrow & FORMAT(Change, "0.0%")
		lineageTag: 7bc74abf-5153-4ca5-b49c-6c994a16cbb6

	measure 'Return Rate Comparison' =
			
			VAR Prev = [PreviousReturnRate(%)]
			VAR Change = [Return Rate Change %]
			VAR Arrow = IF(Change < 0, UNICHAR(9660), UNICHAR(9650))  // ▼ or ▲
			RETURN
			"vs prev: " & FORMAT(Prev, "0.0") & "K / " & Arrow & FORMAT(Change, "0.0%")
		lineageTag: 4789fa85-89fd-4104-9a0d-66c4e0478bd9

	measure 'Previous Profit Marging(%)' =
			CALCULATE(
			    [Profit Margin (%)],
			    DATEADD('Calendar'[Date],-1, YEAR
			    ))
		lineageTag: 4c03d15f-5dc1-437b-8275-0f632216af16

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit Margin Change %' =
			
			VAR _Current = [Profit Margin (%)]
			VAR Previous = [Previous Profit Marging(%)]
			RETURN
			IF(
			    NOT(ISBLANK(Previous)),
			    DIVIDE(_Current - Previous, Previous),
			    BLANK()
			)
		lineageTag: 208a17f0-3ca7-4c2e-974c-0baee21caa4a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit Margin Comparison' =
			
			VAR Prev = [Previous Profit Marging(%)]
			VAR Change = [Profit Margin Change %]
			VAR Arrow = IF(Change < 0, UNICHAR(9660), UNICHAR(9650))  // ▼ or ▲
			RETURN
			"vs prev: " & FORMAT(Prev, "0.0") & "K / " & Arrow & FORMAT(Change, "0.0%")
		lineageTag: 805173a0-ff4c-42a6-ba9a-cf72a63b5a72

	column Column
		formatString: 0
		lineageTag: f7dd9b47-89ae-4c5d-9a30-c0ed0c8ed584
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'KPIs for Card' = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 883e0b19c1794f3bb0098c4c10ed6874

