table 'KPIs Core Sales'
	lineageTag: 29704e9b-242f-493b-8560-c76fa4645ae3

	measure 'Gross Revenue' = ```
			SUMX(SalesData,SalesData[OrderQuantity] * RELATED('Product Information'[ProductPrice])) 
			```
		lineageTag: 74822bde-bf11-449c-bf37-04cfd29db745

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Units Sold' = SUM(SalesData[OrderQuantity])
		formatString: 0
		lineageTag: dfea64df-41c3-47d4-b957-d238ce1418db

	measure 'Total Orders' = DISTINCTCOUNT(SalesData[OrderNumber])
		formatString: 0
		lineageTag: 0af88097-c7e4-4eaa-915b-b708a059e768

	measure 'Avg Order Value' = DIVIDE([Gross Revenue], [Total Orders])
		lineageTag: 9e6906db-6960-418d-bf63-39648a568986

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Previous Month Orders' = CALCULATE([Total Orders],DATEADD('Calendar'[Date],-1,MONTH))
		formatString: 0
		lineageTag: 7ab1419c-bb9b-40cf-a2f3-6cc4e62f6f11

	measure 'Previous Month Profit' = CALCULATE([Gross Profit],DATEADD('Calendar'[Date],-1,MONTH))
		lineageTag: f34cc072-a94d-42b4-bc29-1e6c2c570c90

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales LY :' =
			
			CALCULATE([Gross Revenue],SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: 0
		lineageTag: e55d0e98-1f03-453c-8317-aa78aa1658c1

	measure 'YoY Growth %:' =
			
			DIVIDE([Gross Revenue] - [Sales LY :],[Sales LY :])
		lineageTag: c1f41a2f-4d26-4dd8-ae0d-3ddbf72ec3d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales LM:' =
			
			CALCULATE([Gross Revenue], PREVIOUSMONTH('Calendar'[Date]))
		lineageTag: 9a4ac966-bf13-4d72-9291-344c3804bf35

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MoM Growth %' = ```
			
			VAR SalesLM = [Sales LM:]
			RETURN
			IF (
			    NOT ISBLANK ( SalesLM ) && SalesLM <> 0,
			    DIVIDE ( [Gross Revenue] - SalesLM, SalesLM ),
			    BLANK()
			)
			
			```
		lineageTag: ff4583d7-ba6d-438f-b979-290d69ca7e43

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YTD Sales:' =
			
			CALCULATE([Gross Revenue],DATESYTD('Calendar'[Date]))
		lineageTag: d6093258-3d4f-4123-8776-e0bab0830ee5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YTD Profit:' =
			
			CALCULATE([Gross Profit],DATESYTD('Calendar'[Date]))
		lineageTag: 49b2e78c-ea36-481f-8e6d-7d4197a6f33c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Previous Month Sales' =
			
			CALCULATE([Gross Revenue],DATEADD('Calendar'[Date],-1,MONTH))
		lineageTag: 7e9d8323-559a-4d38-b067-3249503e3d9a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column
		formatString: 0
		lineageTag: 2b4bbf7c-a86e-42b4-8c0b-da65f0c5e39b
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'KPIs Core Sales' = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = a0759bd1eee64a8696992229aa49649f

