table 'Sales Data 2021'
	lineageTag: 8626b9b9-76d8-4a8d-9d63-b9c5b43c7079

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7b1b4e34-9768-4a34-8e2d-0e2067433685
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column StockDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7a87edf0-89ee-4c00-a58f-8486c6e64b34
		summarizeBy: none
		sourceColumn: StockDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OrderNumber
		dataType: string
		lineageTag: 88c22634-5e0e-4c34-9182-42f3132727dc
		summarizeBy: none
		sourceColumn: OrderNumber

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 3b14a39c-c007-49bd-8338-845459d95658
		summarizeBy: count
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: b67b3473-1b22-4164-abe7-19098571123b
		summarizeBy: count
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column TerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: ab13b614-107f-47a7-b7c9-7222f2c9e772
		summarizeBy: count
		sourceColumn: TerritoryKey

		annotation SummarizationSetBy = Automatic

	column OrderLineItem
		dataType: int64
		formatString: 0
		lineageTag: 3e46bb10-a248-489c-b1f0-68708be3d352
		summarizeBy: sum
		sourceColumn: OrderLineItem

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: 6ae38cb9-b543-43f9-a131-d7f13bff7d7f
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	partition 'Sales Data 2021' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\new work space\All Class Video\power bi academy course\Adventure Works Project-20250803T155554Z-1-001\Adventure Works Project\Sales Data\AdventureWorks Sales Data 2021.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"OrderDate", type date}, {"StockDate", type date}, {"OrderNumber", type text}, {"ProductKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"TerritoryKey", Int64.Type}, {"OrderLineItem", Int64.Type}, {"OrderQuantity", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

